# Dependencies
rouge:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Yohan
tagline:          'Coding in python & c#'
description:      'coding in python & c#'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
